services:
  web:
    container_name: recs-seem-web
    tty: true
    restart: always
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    environment:
      - TZ=Asia/Tokyo
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm run dev"
  proxy:
    container_name: recs-seem-proxy
    tty: true
    image: nginx:1.25.4-alpine3.18
    ports:
      - "8080:80"
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=Asia/Tokyo
    command: sh -c "nginx -g 'daemon off;'"
    depends_on:
      - web
volumes:
  node_modules: