import {
  AUTH_ENDPOINTS,
  ORGANIZATION_ENDPOINTS,
  CHAT_ROOM_ENDPOINTS,
} from "./endpoints";

export const ENDPOINTS = {
  ...AUTH_ENDPOINTS,
  ...ORGANIZATION_ENDPOINTS,
  ...CHAT_ROOM_ENDPOINTS,
};
