name: "lint ReCS/SEEM files"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint-code:
    name: Lint typescript files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint
  lint-docker:
    name: Lint dockerfiles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v2.2.0
        with:
          aqua_version: v2.20.0
          policy_allow: true
      - name: Lint app dockerfile
        run: hadolint Dockerfile
  lint-workflows:
    name: Lint github workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v2.2.0
        with:
          aqua_version: v2.20.0
          policy_allow: true
      - name: Ensure that shellcheck is installed
        run: shellcheck --version
      - name: Lint github workflows
        run: actionlint
  check-aqua-checksum:
    name: Check aqua checksum
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v2.2.0
        with:
          aqua_version: v2.20.0
          policy_allow: true
      - name: Update aqua checksum
        run: aqua update-checksum --prune
      - name: Check diff
        run: git diff --exit-code aqua-checksums.json
